version: "3.8"
services:
  keepalived:
    image: osixia/keepalived:2.0.20
    container_name: keepalived
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    environment:
      - KEEPALIVED_UNICAST_PEERS=${KEEPALIVED_UNICAST_PEERS}
      - KEEPALIVED_VIRTUAL_IPS=${KEEPALIVED_VIRTUAL_IPS}
      - KEEPALIVED_PRIORITY=${KEEPALIVED_PRIORITY} 
      - KEEPALIVED_INTERFACE=${KEEPALIVED_INTERFACE:-eno1} 
    labels:
      - autoheal=true
      - com.centurylinklabs.watchtower.enable=true